swagger: '2.0'
info:
  version: v1
  title: cat
  description: cats
host: 'localhost:2002'
basePath: /api
schemes:
  - https
  - http
produces:
  - application/json
paths:
  /cats/v1:
    get:
      tags:
        - Cat
      description: Gets all cats from the system that the user has access to
      operationId: getCat
      produces:
        - application/json
      x-swagger-router-controller: Cat
      responses:
        '200':
          description: cat response
          schema:
            type: array
            items:
              $ref: '#/definitions/catsv1'
        '404':
          description: cat response
          schema:
            type: object
        '500':
          description: cat response
          schema:
            type: object
      parameters:
        - name: pageSize
          in: query
          description: Number of records returned
          type: integer
        - name: pageNumber
          in: query
          description: Page number
          type: integer
    put:
      tags:
        - Cat
      description: Puts all cats from the system that the user has access to
      operationId: putCat
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Cat
      responses:
        '204':
          description: cat response
          schema:
            type: array
            items:
              $ref: '#/definitions/catsv1'
        '404':
          description: cat response
          schema:
            type: object
        '500':
          description: cat response
          schema:
            type: object
      parameters:
        - name: cats/v1
          in: body
          schema:
            $ref: '#/definitions/catsv1'
    post:
      tags:
        - Cat
      description: Posts all cats from the system that the user has access to
      operationId: postCat
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Cat
      responses:
        '204':
          description: cat response
          schema:
            type: array
            items:
              $ref: '#/definitions/catsv1'
        '404':
          description: cat response
          schema:
            type: object
        '500':
          description: cat response
          schema:
            type: object
      parameters:
        - name: cats/v1
          in: body
          schema:
            $ref: '#/definitions/catsv1'
    patch:
      tags:
        - Cat
      description: Patchs all cats from the system that the user has access to
      operationId: patchCat
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Cat
      responses:
        '204':
          description: cat response
          schema:
            type: array
            items:
              $ref: '#/definitions/catsv1'
        '404':
          description: cat response
          schema:
            type: object
        '500':
          description: cat response
          schema:
            type: object
    delete:
      tags:
        - Cat
      description: Deletes all cats from the system that the user has access to
      operationId: deleteCat
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Cat
      responses:
        '204':
          description: cat response
          schema:
            type: array
            items:
              $ref: '#/definitions/catsv1'
        '404':
          description: cat response
          schema:
            type: object
        '500':
          description: cat response
          schema:
            type: object
      parameters:
        - name: cats/v1
          in: body
          schema:
            $ref: '#/definitions/catsv1'
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  catsv1:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      address:
        type: object
        properties:
          streetNumber:
            type: string
          streetName:
            type: string
        required:
          - streetNumber
          - streetName
    required:
      - firstName
      - lastName
      - address
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
          tls-profile: ''
          secure-gateway: false
    catch: []
